package http

import (
	"encoding/json"
	"net/http"

	"github.com/google/uuid"
	"kafka-demo/internal/domain"
	"kafka-demo/internal/service"
)

// HTTPHandler groups all HTTP entrypoints.
type HTTPHandler struct {
	service *service.OrderService
}

// NewHTTPHandler constructs the http handler.
func NewHTTPHandler(svc *service.OrderService) *HTTPHandler {
	return &HTTPHandler{
		service: svc,
	}
}

// CorrelationIDMiddleware extracts or injects a request/correlation ID for transaction tracking.
func CorrelationIDMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reqID := r.Header.Get("X-Request-ID")
		if reqID == "" {
			reqID = uuid.NewString()
		}
		// Write to response header for trace validation
		w.Header().Set("X-Request-ID", reqID)

		// Inject into context.Context
		ctx := domain.WithCorrelationID(r.Context(), reqID)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// ProductHandler handles GET /product requests. Retrieves item details via Cache-Aside.
func (h *HTTPHandler) ProductHandler(w http.ResponseWriter, r *http.Request) {
	name := r.URL.Query().Get("name")
	if name == "" {
		name = "iphone" // Default product
	}

	product, err := h.service.GetProduct(r.Context(), name)
	if err != nil {
		if err == domain.ErrProductNotFound {
			h.writeError(w, "Product not found", http.StatusNotFound)
			return
		}
		h.writeError(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(product)
}

// HealthHandler handles GET /health checks, reporting service status.
func (h *HTTPHandler) HealthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(`{"status":"UP"}`))
}

// CreateOrderRequest defines the schema for the POST /order endpoint.
type CreateOrderRequest struct {
	OrderID string `json:"order_id"`
	Product string `json:"product"`
	Qty     int    `json:"qty"`
}

// OrderHandler handles POST/GET /order requests.
func (h *HTTPHandler) OrderHandler(w http.ResponseWriter, r *http.Request) {
	var req CreateOrderRequest

	// Support POST JSON body parsing, fallback to autogenerated values (compatibility/testing)
	if r.Method == http.MethodPost && r.Body != nil {
		err := json.NewDecoder(r.Body).Decode(&req)
		if err != nil {
			// If JSON is totally invalid, return Bad Request
			h.writeError(w, "Invalid JSON payload: "+err.Error(), http.StatusBadRequest)
			return
		}
	}

	// Apply default values if not specified
	if req.OrderID == "" {
		req.OrderID = uuid.NewString()
	}
	if req.Product == "" {
		req.Product = "iphone"
	}
	if req.Qty <= 0 {
		req.Qty = 1
	}

	err := h.service.CreateOrder(r.Context(), req.OrderID, req.Product, req.Qty)
	if err != nil {
		h.writeError(w, err.Error(), http.StatusInternalServerError)
		return
	}

	w.WriteHeader(http.StatusAccepted)
	_, _ = w.Write([]byte("Order Created\n"))
}

func (h *HTTPHandler) writeError(w http.ResponseWriter, errMsg string, code int) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": errMsg})
}
